camera_info:
  focal_length_x: 1345.200806
  focal_length_y: 1353.838257
  image_width: 800
  image_height: 600
stop_line_positions:
    - [8.0, 16.2]
is_site: True
tensorflow_model: light_classification/frozen_models/frozen_inference_graph_real_tf_v1.4.pb
